controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

send_message:
    path: /api/messages/send
    controller: App\Controller\MessageController::sendMessage
    methods: [POST]